### ISSUE TITLE
Android Image Marker issue

### ISSUE THREAD

**Issue by GrishmaM** [react-native-maps/react-native-maps#2506]
### Is this a bug report?
YES

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
YES

### Environment
react-native => 0.55.0
react => 16.3.1
react-native-maps => 0.16.4

Target Platform:  Android

### Expected Behavior
 the image has to be rendered as a marker

### Actual Behavior
the image is rendered  along with the default red  marker

### Reproducible Demo

      <MapView.Marker
          identifier="Marker"
          image={ markerImg}
          coordinate={coords}
          centerOffset={{ x: -42, y: -60 }}
          anchor={{ x: 0.84, y: 1 }}
          opacity={0.6}
        >

**Comment by jasperkuperus** [comment]
I have a similar issue. From version `0.22.0` on, suddenly the `image={}` of `MapView.Marker` does not render the image. If I start changing images of markers or removing and adding markers, it does work, but the initial render shows the default red pins as markers.

**Comment by ksarkes** [comment]
Still have this issue on 0.22.1

**Comment by marcelkalveram** [comment]
I'm experiencing the same issue. The only solution that seems to work so far is to add the same image outside the MapView and set its height/width to 0.

```<Image source={...} style={{height:0, width:0 }}```

I guess it gets preloaded, so that once the map's onLayout fires, the image is already in cache. I might be wrong, but I haven't seen the default marker fallback since then

Obviously an ugly workaround, but can't think of anything better at the moment.

**Comment by subhashchandrujobop** [comment]
I am also experiencing this issue
