### ISSUE TITLE
marker overflow disappears when using google's map provider

### ISSUE THREAD

**Issue by raphaelbadia** [react-native-maps/react-native-maps#2588]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

Node: 10.5.0
npm: 6.1.0
react: 16.6.0-alpha.8af6728
react-native: 0.57.3
react-native-maps: 0.22.0

### Steps to Reproduce

Set up a new map with google provider
```
<MapView
                    initialRegion={{
                        latitude: 37.802214938534505,
                        longitude: -122.42416240009591,
                        latitudeDelta: 0.0922,
                        longitudeDelta: 0.0421,
                    }}
                    ref={this.props.setMapViewRef}
                    onRegionChangeComplete={this.handleRegionChange}
                    provider={PROVIDER_GOOGLE}
                    style={styles.map}
                >
```

Put a custom marker on the map, put an image inside and put it half out of the box

### Expected Behavior

I developped custom markers and callouts that look like this on ios 's apple map:
![image](https://user-images.githubusercontent.com/1901628/48637005-c4411580-e9cc-11e8-9ca4-f7948247051b.png)

It should be identical using google's map provider

### Actual Behavior

I followed the installation and added `provider={PROVIDER_GOOGLE}` to my `MapView` and reloaded the app.

The map style is applied but everything out of the boxes has disapeared: 
![image](https://user-images.githubusercontent.com/1901628/48637131-0b2f0b00-e9cd-11e8-8b12-79087a1a09c8.png)

I do the same thing somewhere else in my app, looks like it's a problem related to marker

**Comment by raphaelbadia** [comment]
I ended up using apple's map

**Comment by LaVielle** [comment]
Any update on this issue?

My setup
rn maps 0.25.0
rn 0.59.9

I have the same problem, shadow is being cut because overflow is hidden for some reason.
I see this problem on iOS.
Could this be something we can configure in JSON we pass to the `customMapStyle` prop?
<img width="174" alt="Screen Shot 2019-07-26 at 10 46 58 AM" src="https://user-images.githubusercontent.com/22463797/62194619-80374a80-b37a-11e9-8f4a-b7c1eee6ed23.png">

**Comment by sbichenko** [comment]
Can we reopen this issue? It is not actually resolved, since the Google's map provider indeed does cut off the content, and there doesn't seem to be a workaround.

**Comment by rafaelbpa** [comment]
2021 still not working, can we reopen this, please?

**Comment by McCaffertyp** [comment]
Feb 2022, still not working. Would appreciate if this could be reopened, please?

**Comment by raphaelbadia** [comment]
Well I reopened it but I think you should create a new issue because I don’t have the project anymore 😅

**Comment by McCaffertyp** [comment]
Oh no haha. Thanks for the reopen though. To temporarily get around this issue, for anyone who see's this, I'm temporarily doing this - Went ahead and created a View wrapper for the custom marker that had a height and width to fit everything inside, positioned everything as wanted, and then to adjust for any marker movement happening due to the wrapper's set width and height, I just used the Marker prop types "anchor" for Android adjustment and "centerOffset" for iOS adjustment.

`const backgroundColorStyle = {
    backgroundColor: selectedMarkerId === marker.id ? Colors.selectedBlue : getMarkerDisplayColor(marker)
}
const colorStyle = {
    backgroundColor: getMarkerFadedDisplayColor(marker),
    borderColor: getMarkerDisplayColor(marker)
}
const opacityStyle = {
    opacity: props.markerDisplayAnimations.current[i].opacityAnimation
}
const scaleStyle = {
    transform: [{ scale: props.markerDisplayAnimations.current[i].scaleAnimation }]
}
return (marker.display && (marker.title.includes(props.eventSearch) || marker.type.includes(props.eventSearch)) &&
    <Marker
        identifier={i.toString()}
        key={i}
        tracksInfoWindowChanges={true}
        style={{ zIndex: selectedMarkerId === marker.id ? 3 : 2 }}
        coordinate={{
            latitude: marker.latitude,
            longitude: marker.longitude
        }}
        anchor={{ x: 0.51, y: 0.59 }}
        centerOffset={{ x: 0.51, y: 0.59 }}
    >
        <Animated.View style={[styles.baseMarkerWrap, opacityStyle]}>
            <Animated.View style={[styles.baseMarkerRing, colorStyle, scaleStyle]} />
            <View style={[styles.baseMarkerStyle, backgroundColorStyle]} />
        </Animated.View>
    </Marker>
)`

then the styles:
`baseMarkerWrap: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center"
},
baseMarkerStyle: {
    width: 12,
    height: 12,
    borderRadius: 10
},
baseMarkerRing: {
    position: "absolute",
    width: 25,
    height: 25,
    borderWidth: 1,
    borderRadius: 48
},`

Since the overflow of the scaling was being cutoff, I made the wrap slightly bigger than the max width and height the scale would go to and then adjusted the marker downwards to make up for the height adjustment. Don't know if this will help anyone, but hopefully at least one person may find it useful.

**Comment by ayoub-rouani** [comment]
2025 still not working, can we reopen this, please?
