### ISSUE TITLE
Android animateMarkerToCoordinate strange behavior

### ISSUE THREAD

**Issue by thiagovictorino** [react-native-maps/react-native-maps#2642]
### Is this a bug report?

Maybe

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
 "react": "16.6.3",
 "react-native": "0.57.8",
 "react-native-maps": "^0.22.1",
 "react-native-maps-directions": "^1.6.0"

Target Platform: Android Motorola MotoE2 (4G LTE) Android 6.0 API 23

### Steps to Reproduce

I have an issue that I don't know how to solve or if it could be a bug. I am using the code example describe [here](https://github.com/react-native-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js) and I did some modification to pass a list of positions to move that marker thru this positions.

My entire code [is here](https://gist.github.com/thiagovictorino/2c6d8523308c40eb8964949639c4e31e) 

The problem is that when I called the animateMarkerToCoordinate method, the marker shake like a crazy as you can see in [this video](https://www.youtube.com/watch?v=3xhxCKDGSuU&feature=youtu.be) at second 3.

In that video, the device is using a compiled APK.

Have someone idea what's could help me?

**Comment by juergengunz** [comment]
same issue, @thiagovictorino did you find a way to fix that?

**Comment by hussainahmad** [comment]
I am also getting the same strange crash due to `animateMarkerToCoordinate` . ,, as the [docs](https://github.com/react-native-community/react-native-maps#animated-marker-position) suggested use `animateMarkerToCoordinate` for moving marker on android, getting crash 
![Screenshot_1578395039](https://user-images.githubusercontent.com/5903522/71892957-24b08a80-316c-11ea-9b90-ac88d301ba87.png) don't know the reason as no supportive sys-trace .
