### ISSUE TITLE
Error while updating property 'mapType' of view managed by: AIRMap

### ISSUE THREAD

**Issue by reinvanimschoot** [react-native-maps/react-native-maps#2654]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.57.7
react: 16.6.3
react-native-maps: 0.22.1

target platform: Android Emulator

### Steps to Reproduce

I just added a 

```
  <MapView
    initialRegion={{
      latitude: 37.78825,
      longitude: -122.4324,
      latitudeDelta: 0.0922,
      longitudeDelta: 0.0421,
    }}
  />
```
And got this error. 

### Expected Behavior

Since it works perfectly on iOS, I assumed it would be the same on Android. When I dismiss the error, I do see the map on Android so I do think that the installation went well.

### Actual Behavior

I got this red screen error: 
`Error while updating property 'mapType' of view managed by: AIRMap`

<img width="473" alt="screenshot 2019-01-11 at 12 01 38" src="https://user-images.githubusercontent.com/35171567/51030415-a7265e80-1599-11e9-82fd-bec8ea33b4e5.png">

I tried adding/removing multiple options such as `mapType="standard"` but nothing works.

**Comment by johhansantana** [comment]
Have you found a solution?
This only happens to me when I put:
```
mapType={"mutedStandard"}
```

If I use any other `mapType` it works normally.

This only happens on Android though.

**Comment by muratonay1** [comment]
have you found any solution?

**Comment by MoeMamdouh** [comment]
in Android, You should assign `mapType` to Value if `null` it will crash

So this:
```
mapType={isSatellite ? 'satellite' : null}
```
Should updated to:
```
mapType={isSatellite ? 'satellite' : 'standard'}
```

**Comment by Livijn** [comment]
> Have you found a solution? This only happens to me when I put:
> 
> ```
> mapType={"mutedStandard"}
> ```
> 
> If I use any other `mapType` it works normally.
> 
> This only happens on Android though.

This was the reason for me aswell.

**Comment by Samidolla** [comment]
guys any solution

**Comment by AyushBawane** [comment]
i was using it like 'mutedStandard' (in single quotes) and it was throwing same error,
then put it in double quotes like, "mutedStandard" and tada... error was resolved..  :-|)

**Comment by DolenDeori** [comment]
I had the same problem since I am working on android. the mapView = "mutedStandard" only works on iOS as mention in the guide.

The map type to be displayed.

- standard: standard road map (default)
- none: no map Note Not available on MapKit
- satellite: satellite view
- hybrid: satellite view with roads and points of interest overlayed
- terrain: topographic view
- mutedStandard: more subtle, makes markers/lines pop more (iOS 11.0+ only)
- satelliteFlyover: 3D globe with sattelite view (iOS 13.0+ Apple Maps only)
- hybridFlyover: 3D globe with hybrid view (iOS 13.0+ Apple Maps only)

This is the guide : https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md
you can read here.

Hope this helps 👍
