### ISSUE TITLE
Control MapView.Callout visibility with a prop

### ISSUE THREAD

**Issue by athaeryn** [react-native-maps/react-native-maps#275]
I'd like to have more precise control over whether callouts are open. Would it be technically possible (I could submit a PR if given a little starting direction) to control the visibility of the callout with a prop, or would I need to maybe render the component within my marker and toggle the visibility that way?

**Comment by alvelig** [comment]
https://github.com/react-community/react-native-maps/issues/34#issuecomment-174248813

**Comment by lukasgjetting** [comment]
@athaeryn Did this ever get anywhere? I can't seem to find anything in the docs.

**Comment by miracle2k** [comment]
I tried to give it a go, but as far as I can tell, at least on MapKit, the problem seems to be that MapKit itself does not allow multiple callouts to be visible at the same time. 

Or, after more investigation, since we use our own callout implementation, I think that the problem really is that we only have a single callout view, bound to the map instance, and that one is moved around. 

We would rather need to give every marker their own instance of the callout view, or the best we might be able to do is to accept this limitation and instead add a property to the map, `openCallout=${marketIdentifer}` to control which callout is open.

**Comment by wjielim** [comment]
I guess the only "clean" way is to use custom view as marker like [this](https://github.com/react-community/react-native-maps#arbitrary-react-views-as-markers), source code [here](https://github.com/react-community/react-native-maps/blob/master/example/examples/ViewsAsMarkers.js)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by Luccasoli** [comment]
I need to show a component only when the map shows some Callout. This issue can it be reopened?

**Comment by piotrgomola** [comment]
@christopherdro can you reopen the ticket? Relative enhancement tickets were opened but systematically closed redirecting to this one and this one is also closed as well, without any specific solution for tracking callout view visibility.

**Comment by NeliHarbuzava** [comment]
Need the possibility to show callouts for multiple markers at the same time. For now, it is possible to show only one callout with `showCallout()` method. When `showCallout` called, another callouts got hidden. How we can implement this?

**Comment by alainib** [comment]
still got this issu in 2023 :(

**Comment by Schitzos** [comment]
is there any update to open all callout in same time?
