### ISSUE TITLE
re-render polyline when onRegionChangeComplete

### ISSUE THREAD

**Issue by MRSEREY** [react-native-maps/react-native-maps#2951]
# Question

I am using google direction api (https://maps.googleapis.com/maps/api/directions/json) to get waypoints and draw polyline. It does well for short distance but for long distance when I was zooming in I noticed that the polyline did not draw correctly.

any ideas or helps plz.

**Comment by bramus** [comment]
You are most likely drawing the overview polyline, instead of the detailed one.

Be sure to also take a peek at https://github.com/bramus/react-native-maps-directions, a library that does directions/routing for you. It can render the detailed polyline for you, by setting `precision="high"` on the component.
