### ISSUE TITLE
animateToRegion should have a callback argument

### ISSUE THREAD

**Issue by jumpman255** [react-native-maps/react-native-maps#2984]
# Feature Request

## Why it is needed

Would make possible to do something after the animation.

## Possible implementation

Add a callback param in animateToRegion that's get executed after the animation is played.

### Code sample

mapRef.animateToRegion(region, duration, callback)

**Comment by outaTiME** [comment]
+1

**Comment by nabati** [comment]
Out of curiosity, what do you want to use it for?

**Comment by raphaelv1** [comment]
Callbacks after animations are pretty common and can be useful in multiple situations. As an example, if I use it to center the camera on a coordinate, I could use the callback to know when the camera is now centered.

**Comment by richardbumm** [comment]
@nabati 
I would use it to search that new region automatically when the animateToRegion has finished, or if someone selects a location, the map animates there, open the callout during the callback function.

**Comment by zchwyng** [comment]
+1

**Comment by craig8two** [comment]
+1

**Comment by ezranbayantemur** [comment]
+1

**Comment by deniscreamer** [comment]
+1

**Comment by gurkanguran** [comment]
+1

**Comment by riccardolardi** [comment]
+1

**Comment by victor9000** [comment]
You can use MapView's onRegionChange and onRegionChangeComplete for this purpose, as these events are also fired when using animateToRegion.

**Comment by kub1x** [comment]
Hey, let me describe my use case. To me it feels it can not be achieved without callback or promise on the `animateToRegion` function. 

I'm implementing my own `followsUserLocation` functionality. The docs say it is Apple only and I want my custom user location icon anyway. 

I'm using `animateToRegion` to navigate the map to users current position, when a "zoom to current location" button is pressed. Since then, I want the map to follow users location (using `useEffect` and the same zooming function). If `animateToRegion` was async function and/or had a callback, I would call my `setFollowUserLocation(true)` state function when the animation is done. I'm currently doing it using `setTimeout` (with timeout slightly longer than the animation duration) which is just sad. 

I use `onRegionChange` to unset the `followUserLocation` flag when user drags the map manually, or presses my other button to zoom elsewhere (specifically to zoom to see all the POIs on the map). 

Perhaps I'm missing some other easy way to implement this without callback, but I can't really see it.

**Comment by Rileyp33** [comment]
Chiming in here because I had issues implementing both `animateCamera` and `animateToRegion` together because there's no way to know when the animation is finished (long story, but I can't just use the `center` property in `animateCamera` -- I need to set `latitudeDelta` and `longitudeDelta` dynamically).

I was able to implement a pseudo-callback on `animateToRegion` using React Native's `InteractionManager`:

```
this.mapRef?.animateToRegion({
  latitude,
  longitude,
  latitudeDelta,
  longitudeDelta,
})

InteractionManager.runAfterInteractions(() => {
  this.animateHeading()
})
