### ISSUE TITLE
Map callout jumps when marker clicked - iOS

### ISSUE THREAD

**Issue by ryanjorgensen** [react-native-maps/react-native-maps#3047]
# Bug

When using iOS maps, markers that are near each other will jump to near marker (and render callout) when tapped.

![gif of bug](https://media.giphy.com/media/elDItzq2vyN0dwFZ2k/giphy.gif)

## Environment info

Expo is using react-native-maps 0.22.1 but this behavior happens in the latest release (0.25.0) as well.

## Steps To Reproduce
Run the linked snack below, tap one of the markers on the left side.

## Reproducible sample code
Tiny snack reproducing this issue
https://snack.expo.io/@jorgensenr/adequate-scones

## References
#2492

**Comment by ryanjorgensen** [comment]
#2492

**Comment by ReneMoraales** [comment]
I am having this same issue and it has been posted multiple times here, under different descriptions, always with no response.

**Comment by cokron** [comment]
I have the same issue. iOS only.

Interestingly, the `onPress(…)` event is only fired for the marker I have really clicked on. But the `onSelect(…)` event is fired for _both the marker I clicked on to open the callout + the neighbouring marker_.

I did some research and it seems that the error was introduced here (as mentioned by leonardogutierrezh in a comment to the PR):
https://github.com/react-native-community/react-native-maps/pull/1079

There is a strange workaround here: https://github.com/react-native-community/react-native-maps/issues/1353 (set `pointerEvents="auto"`, which worked for me, but makes appearance of callout slow.).

This issue is a duplicate of https://github.com/react-native-community/react-native-maps/issues/2492 and https://stackoverflow.com/questions/52293052/jumping-markers-jumping-to-next-or-nearest-marker-in-react-native-maps?rq=1.

**Comment by abhinavpadala** [comment]
I am facing the same issue on an Android device.  Is there a work-around to fix this?:)

**Comment by javi242** [comment]
I am having the same issue. Not fixed yed? Any help would be great. Thanks.

**Comment by ACV2** [comment]
i'm having the same issue. when clicking on pins that are close to each other, the one next to the tapped one is the one actually highlighted, weird but consistent to which was described on this thread
