### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by benjamin-sweney** [react-native-maps/react-native-maps#3074]
# Question

I'm currently struggling with a couple performance issues so have forked the branch so I can develop these features on the native side. However, there doesn't appear to be any Contribution Guidelines or the likes on how to get started. I have very limited iOS development knowledge and don't even know how to get started. 

Ideally I would be able to develop the features I require in Swift so would be awesome if someone could point me in the direction of setting up the bridging header. 

Thanks!

**Comment by leecommamichael** [comment]
As an iOS native dev, I second this.

I cloned the project and there does not appear to be an opinionated way (No cartfile or podspec) to acquire the (not committed) React headers for developing the iOS native module. The React Native documentation for developing Native Modules is not very helpful, either.

**Comment by leecommamichael** [comment]
I'm also having trouble with this, here's where I'm at so far. I want to push a small change to the iOS native code and then test it in my react-native app.

1. `git clone https://github.com/react-native-community/react-native-maps`
2. `cd react-native-maps && yarn install`
3. open `lib/ios/AirMaps.xcodeproj`
4. drag and drop the `node_modules/react-native/React/React.xcodeproj` into `AirMaps` in Xcode
5. link with `libReact.a`
![Screen Shot 2019-09-27 at 2 53 18 PM](https://user-images.githubusercontent.com/13748676/65798217-af79f600-e136-11e9-9da4-de5cafd6761d.png)

I added the React xcode project to AirMaps because I knew that would resolve the missing headers in the project, I added `libReact.a` to be linked because though the headers may be available, the implementation of those header's declarations would need to be compiled with AirMaps.

Now when I run the built target from Xcode, Metro starts up and the Xcode build succeeds That's where I'm stuck, how to use the built product? I suppose I'll look for some built product and try to copy it into the `node_modules` folder of my example app? I'm unsure.

![Screen Shot 2019-09-27 at 2 59 45 PM](https://user-images.githubusercontent.com/13748676/65798523-79894180-e137-11e9-8796-9039c66f639c.png)
