### ISSUE TITLE
Detecting what triggered onRegionChangeComplete

### ISSUE THREAD

**Issue by mbrucher** [react-native-maps/react-native-maps#3112]
# Feature Request

I would like to have a way of detecting what triggered `onRegionChangeComplete`.

## Why it is needed

It would be great to detect if `onRegionChangeComplete` is triggered by the user dragging the screen, or if it was triggered by changing `region`. Typically, changing `region` from `onRegionChangeComplete` can lead to oscillations in the display when the state is changed using a tool like redux. 

## Possible implementation

We could have a tag on the generated event.

### Code sample

No example yet!

The feature may exist already, if that's the case, sorry for this, but it's not obvious from the documentation!!

**Comment by Fghurayri** [comment]
I was in a similar place as you. From my understanding, the feature doesn't exist. 

I needed to run certain code only if the region has changed due to user's panning AND NOT due to programmatically changing the region (like using `fitToCoordinates` or `animateCamera`)

It would be nice if all the methods that change the region programmatically would have an extra param to indicate whether `onRegionChangeComplete` should be invoked or note AFTER the region changed successfully.

I have implemented the following hack:

- In the component's state:

```js
  state = {
    isDraggingMap: false,
  };
```

- In the render method:

```js
<MapView
          [...]
          onPanDrag={this.setMapDragging}
          onRegionChangeComplete={this.onRegionChangeComplete}
/>
```

- In both handlers:

```js
  setMapDragging = () => {
    if (!this.state.isDraggingMap) {
      this.setState({
        isDraggingMap: true,
      });
    }
  };

  onRegionChangeComplete = async () => {
    if (this.state.isDraggingMap) {
      this.setState({
        isDraggingMap: false,
      });
    }

    if (!this.state.isDraggingMap) {
      return;
    }

    // your desired code to be run ONLY due to user's panning.
  };
```

The above is tested on iOS and Android for react-native-maps @ v26.1.0 with react-native @ v.0.61.1

**Comment by mbrucher** [comment]
Agreed!
Does this work for zooming in/out as well? (i.e. is MapDragging also triggered when zoom starts?)

**Comment by ptcasa** [comment]
<img width="688" alt="zoom-out-n-move" src="https://user-images.githubusercontent.com/11376297/68067943-457ded80-fd81-11e9-96c8-690646f14a4f.png">
I tested by zoom out with iphone X on ios 13 simulator, there are a list of region when moving map. Is it a bug ? how can we resolve it ?

**Comment by dmitryshelomanov** [comment]
@ptcasa +1
