### ISSUE TITLE
Is it possible to update Coordinate Reference System (CRS)?

### ISSUE THREAD

**Issue by hussainahmad** [react-native-maps/react-native-maps#3240]
# Question

I want to update the CSR value for loading the map like I want to load yandex map through `UrlTile` , but to show marker on exact location I need to change the CSR value to `CRS.EPSG3395` which I found no help to do this with this library. Any help in this regard is appreciated

**Comment by kriscarle** [comment]
If Yandex tiles are EPSG:3395 instead of the standard EPSG:3857 then I'm not sure they are compatible for overlaying on Google/Apple Maps. If they display at all they will probably be distorted and coordinates for markers and GPS will not display in the correct locations.

You'll probably have to use this https://tech.yandex.com/maps/mapkit/ If you are using Expo that will also mean exporting to a native app.
