### ISSUE TITLE
google maps icon appearing in maps

### ISSUE THREAD

**Issue by js08** [react-native-maps/react-native-maps#3482]
Hi,

I am attaching two different screenshots of android mobile, where I am seeing different icons in react-native-maps.

When map reaches the store I am making one api call and changing the state to arrived, that point of time I am seeing google maps icon, directions icon and the compass icon. this icons also appear for a few seconds and disappears

In another screenshot when the truck is in the departed state, I don't see icons.

Can you let me know how to disable the icons or is it a bug when I am changing the state  

![google-text](https://user-images.githubusercontent.com/1699943/85795280-a20d8e80-b6fd-11ea-8326-2283408cc599.png)
![google-map-directions-icon](https://user-images.githubusercontent.com/1699943/85795297-a46fe880-b6fd-11ea-8d85-ba7179635b1d.png)

**Comment by dpz3579** [comment]
Please go through 

[MapView documentation] (https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md)

you can set values to 
```
showsCompass,
showsBuildings,
showsTraffic,
```
and various other props while loading your MapView component.

I hope this solves your issue.

And since there is no label assigned for this issue, the Team will mark it as closed.
