### ISSUE TITLE
undefined is not an object (evaluating 'this.map.setNativeProps')

### ISSUE THREAD

**Issue by samuelhulla** [react-native-maps/react-native-maps#3663]
# Bug report

## Summary

The `MapView` component crashes on mount, specifically 

> Component Exception: undefined is not an object (evaluating 'this.map.setNativeProps')

## Environment info

```
react-native: 0.63.3
react: 16.13.1
react-native-maps: 0.27.1
```

## Steps to reproduce

Normal usage react-native usage:

1. Installation of node_modules (`yarn`)
2. Installation of pods `cd ios && pod install && cd ..`
3. Run the build `npx react-native run-ios` (or run-android, doesn't matter)

Describe what you expected to happen:

 - Previously the `MapView` worked as expected.  
 - This issue occured after upgrading react-native version

Describe what you actually happens:

- Now the entire build crashes instantly on `MapView.js` mount with the aforementioned error

![image](https://user-images.githubusercontent.com/17268815/102894816-f652ba80-4463-11eb-8294-7ccbc50878bc.png)

## Reproducible sample code

```jsx
import MapView, { Marker, PROVIDER_GOOGLE } from 'react-native-maps'
/* i've also checked all the props during debugging and they are defined
 * they're passed via props (including the coordinates)
*/
// later...
return (
        <MapView
          provider={PROVIDER_GOOGLE}
          showsUserLocation
          initialRegion={{
            latitude: coordinates.latitude,
            longitude: coordinates.longitude,
            latitudeDelta: 0.006, // TODO determine this in some better way
            longitudeDelta: 0.006, // TODO determine this in some better way
          }}>
          <Marker
            identifier='example'
            title='example'
            description='here'
            coordinate={{
              latitude: coordinates.latitude,
              longitude: coordinates.longitude,
            }}
            // Auto-selecting the marker when reference is available
            ref={ref => ref && ref.showCallout()}
          />
        </MapView>
)
```

**Comment by atomicman57** [comment]
I am having the same issue

**Comment by PeterVNguyen** [comment]
If you are using GoogleMapService for iOS, you can check again [INSTALLATION](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions) for GoogleMap on iOS

**Comment by SpQuyt** [comment]
> If you are using GoogleMapService for iOS, you can check again [INSTALLATION](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions) for GoogleMap on iOS

Thank you. I forgot to add GG API KEY in `AppDelegate.m`, now my map has been running <3

**Comment by nicholasmarais1158** [comment]
I noticed these symptoms when I configure my Podfile incorrectly while following the [install guide](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions).

I had this;
`pod 'react-native-maps', :path => '../node_modules/react-native-maps'`

Instead of this;
`pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'`

Also, I didn't **need** to include the lines below, as these are picked up from the `react-native-google-maps` pod. Although, it doesn't use the latest versions. 🤷 
```
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
```

**Comment by denishgcirklestudio** [comment]
I'm getting the same issue even if i've assigned provider in `MapView`.

**Code**
```
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'

<MapView
      provider={PROVIDER_GOOGLE}
      ...
```

Purpose of this is, i want to use only google map in android and iOS as well.

**Podfile**

```
  pod 'GoogleMaps', '4.2.0'
  pod 'GooglePlaces', '4.2.0'
  pod 'Google-Maps-iOS-Utils'
```

**package.json**

```
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-maps": "0.27.1"
```

**Comment by nicholasmarais1158** [comment]
@denishgcirklestudio Have you included the line below in your **Podfile**?
```
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
```

See **Enabling Google Maps on iOS (React Native all versions)** point **c)**; [install guide](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions)

**Comment by denishgcirklestudio** [comment]
> @denishgcirklestudio Have you included the line below in your **Podfile**?
> 
> ```
> pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
> ```
> 
> See **Enabling Google Maps on iOS (React Native all versions)** point **c)**; [install guide](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps-on-ios-react-native-all-versions)

Thank you. I resolved the issue. 😃

**Comment by marcozciuffini** [comment]
All of the above advice is helpful/necessary, the one final thing I had to confirm elsewhere was the 'include the Google maps library in your build' step in the installation steps. 

For this, in Xcode, I had to right click on my **project** in the Project Navigator o the left hand side, "Add files to PROJECT_NAME" and add the air google maps in node_modules -> react-native-maps -> lib -> ios -> AirGoogleMaps 

<img width="270" alt="Screenshot 2021-04-09 at 10 40 43" src="https://user-images.githubusercontent.com/46537975/114161655-3ad56980-9920-11eb-9a13-ff91da573cdb.png">

Thank the gods, because my apple maps configuration was just taking me to wrong place. Regardless of the input, it was taking me to somewhere called Moffat in the north of England

**Comment by danieldanielecki** [comment]
`pod install` has installed for me the missing pods:
```
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
```
in combination with the [installation guide](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md) it fixed the issue :)
