### ISSUE TITLE
Circle

### ISSUE THREAD

**Issue by hafeez-ullah-khan** [react-native-maps/react-native-maps#3699]
# Question

i am creating three **Circle** around user location with different colors,
 it works fine in android, 
but in **IOS** the color are showing sometimes and sometimes it not showing the actual color i have implemented.

![Simulator Screen Shot - iPhone 11 - 2021-02-02 at 15 34 45](https://user-images.githubusercontent.com/66471936/106609891-178ee680-658c-11eb-8429-a0397bf2a017.png)

this one is what i am getting some time. IOS only
![Simulator Screen Shot - iPhone 11 - 2021-02-02 at 15 38 13](https://user-images.githubusercontent.com/66471936/106610285-984de280-658c-11eb-8782-5d527821e146.png)

**Comment by gavin-rose** [comment]
Can you please post a code snippet or a snack? Considering it works fine on android, I would guess that iOS is having a problem parsing through your color arguments some of the time.

**Comment by MoSanogo** [comment]
Can I have access to your code base for this issue. It would be much easier to help you out?
I have looked at your repositories to have access it but there is nothing there .

**Comment by MoSanogo** [comment]
Hi hafeez-ullah-khan!!
I do not know what you are using as simulator to build your app  but I dare guess you are you are using expo to .
Here are the snippet of codes that I have used to simulate your case .It happens that the expo simulators android and ios do not know display the circle with its colors but on my real devices Android and IOS ,it works fine .
I do believe that the problem is not with react-native-maps library.




`import  React,{useEffect,useState} from 'react';
import MapView, { PROVIDER_GOOGLE ,Circle} from 'react-native-maps'
import { StyleSheet, Text, View, Dimensions } from 'react-native';

export default function App() {
  const [{height,width},setDimensions]=useState(()=>{
    const {height,width}=Dimensions.get('window');
    return {height,width};
  })
  useEffect(()=>{
    const getDimensions=()=>{
           const {height,width}=Dimensions.get('window');
           setDimensions({height,width})
         }
         Dimensions.addEventListener("change",getDimensions)

         return ()=>{
           Dimensions.removeEventListener("change",getDimensions)
         }
  },[])

  return (
    <View style={styles.container}>
      <MapView style={[styles.map,{width:width*0.9,
    height:height*0.9},]}
      provider={ PROVIDER_GOOGLE} 
       initialRegion={
         {longitude:-73.84111781714093,
         latitude:45.64834003187947,
         latitudeDelta:0.01,
         longitudeDelta:0.02}
      }
     >
    <Circle
    center={
      {longitude:-73.84111781714093,
      latitude:45.64834003187947}
    }
     radius={600}
     strokeColor="red"
 
    />
      <Circle
    center={
      {longitude:-73.84111781714093,
      latitude:45.64834003187947}
    }
     radius={60}
     strokeColor="blue"
   
    />
      <Circle
    center={
      {longitude:-73.84111781714093,
      latitude:45.64834003187947}
    }
     radius={250}
     strokeColor="green"
     
    />
     </MapView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  map: {
    
  },`
 
Please ,try your code on an ios real physical device and I am sure that you will come to the conclusion.

**Comment by avlonder** [comment]
Use setNativeProps as a workaround

**Comment by christopherdro** [comment]
Please use this issue tracker for bug reports and features. Questions are better suited for Stack Overflow.
Thanks!

**Comment by AhmedHF** [comment]
> Use setNativeProps as a workaround

how to apply this?
please example
