### ISSUE TITLE
MapView crashes after deploy to Google Play (production)

### ISSUE THREAD

**Issue by smartbayaraa** [react-native-maps/react-native-maps#3776]
Hi,

I am using MapView on the Expo project. When I deployed to Google Play, our app is crashed.

Is it depending on "config.googleMaps.apiKey" configuration? Should I create a new release after change this property? or can use the following command "expo publish"?

How can I reproduce this error on production?

Thanks.

**Comment by sami-99** [comment]
same issue for me

**Comment by smartbayaraa** [comment]
> same issue for me

Did you find any solution? Now I'm creating a new release with the above configuration. I will tell you after approve my release and test it.

**Comment by MaRaSu** [comment]
In Expo docs [Mapview Expo docs](https://docs.expo.io/versions/v40.0.0/sdk/map-view/) it says pretty clearly what you need to do to enable Mapview in a standalone app. Otherwise standalone app will crash. So yes, you need `config.apiKey` and a couple of other things.

As for `expo publish`, again, documentation at [Publishing Expo docs](https://docs.expo.io/workflow/publishing/) makes it pretty clear that many of the changes in `app.json` config require re-building rather than just publishing.

Expo has pretty comprehensive and easy to understand docs. Recommend spending a bit of quality time at least in glancing through them.

**Comment by christopherdro** [comment]
https://docs.expo.io/versions/v40.0.0/sdk/map-view/#deploying-to-the-google-play-store

**Comment by smartbayaraa** [comment]
Hi, Guys.

I followed every step very carefully, but no luck.

* If you already have Google Sign In configured
* If you have not configured Google Sign In
* Deploying to the Google Play Store

Help me reproduce it?

Thanks

**Comment by smartbayaraa** [comment]
I found a problem with android.

@sami-99 it is a Marker problem. 

I just installed adb and debug it.

<Marker> <Image/> </Marker> instead of  <Marker image={}/>

Thanks @MaRaSu

**Comment by sami-99** [comment]
> In Expo docs [Mapview Expo docs](https://docs.expo.io/versions/v40.0.0/sdk/map-view/) it says pretty clearly what you need to do to enable Mapview in a standalone app. Otherwise standalone app will crash. So yes, you need `config.apiKey` and a couple of other things.
> 
> As for `expo publish`, again, documentation at [Publishing Expo docs](https://docs.expo.io/workflow/publishing/) makes it pretty clear that many of the changes in `app.json` config require re-building rather than just publishing.
> 
> Expo has pretty comprehensive and easy to understand docs. Recommend spending a bit of quality time at least in glancing through them.

I'm using CLI.
The issue is only in the apk version

**Comment by sami-99** [comment]
> I found a problem with android.
> 
> @sami-99 it is a Marker problem.
> 
> I just installed adb and debug it.
> 
>  instead of
> 
> Thanks @MaRaSu

so you got the solution?

**Comment by nknaveen007** [comment]
@sami-99 me too
