### ISSUE TITLE
Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

### ISSUE THREAD

**Issue by kodeandoec** [react-native-maps/react-native-maps#3983]
# Bug report
[](url)

## Summary

`Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1201
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498
__RCTExecuteOnMainQueue_block_invoke
82506F82-C97A-3CF2-BA6C-ACA532D8AA49
82506F82-C97A-3CF2-BA6C-ACA532D8AA49
_dispatch_main_queue_callback_4CF
0E00CA08-C176-30F7-9CF9-445B374C0686
0E00CA08-C176-30F7-9CF9-445B374C0686
CFRunLoopRunSpecific
GSEventRunModal
280B8BEE-0493-3862-B922-9A87C5F46EE8
UIApplicationMain
main
start`

## Environment info

```bash
"react-native": "0.66.1",
      "react": "17.0.2"
      "react-native-maps": "^0.29.3",
```

## Steps to reproduce

npx react-native run-ios

when return screen have this issue

## Reproducible sample code

<MapView
              initialRegion={{
                latitude: -1.395197,
                longitude: -78.423335,
                latitudeDelta: 0.009999,
                longitudeDelta: 0.009999,
              }}
              style={{height: 200}}
              provider={PROVIDER_GOOGLE}
              customMapStyle={mapStandardStyle}
              showsUserLocation={true}
            >
              <Marker
                coordinate={{
                  latitude: latitude,
                  longitude: longitude,
                }}>
                <Image
                  resizeMode="cover"
                  style={styles.marker}
                  source={require('../../../../assets/img/map-pin.png')}
                />
              </Marker>
            </MapView>

**Comment by ramisalem** [comment]
Same issue

**Comment by benkhlifafahmi** [comment]
same issue here

**Comment by mxmtsk** [comment]
Same here, did anyone find a solution?

I noticed that this does not happen in Debug Mode in simulator. It also doesn't happen when I use the arrays `index` as a key. If I use another property, like an `id`, the error appears:

Works:

```js
            {results &&
              results.map((entry, index) => {
                return <PubMapMarker key={index} pub={entry} />;
              })}
```

Does not work:

```js
            {results &&
              results.map((entry) => {
                return <PubMapMarker key={entry.id} pub={entry} />;
              })}
```

**Comment by croaker** [comment]
Using the Apple Maps implementation on iOS solves the problem for me (i.e. dropping the `provider={GOOGLE_PROVIDER}` prop).

**Comment by ingvardm** [comment]
This happens only when the marker has children

**Comment by vkorpas** [comment]
Any solution??

**Comment by salah-ghanim** [comment]
This is not an issue regarding this project, instead it's an implementation detail difference between GoogleMaps and apple MapKit on iOS.

mainly Apple MapKit supports UIView object inside markers, it knows how to display them. which means if you create a react element inside the marker <Image> in the above example a UIKit view element is created UIImage and added when AppleMaps is used.

but Google Maps don't support native UIKit Views (I think they even render using openGL). so when react native tries to create a view inside the Marker .. everything breaks.

this project at the end of the day is limited by what is possible via the native maps libraries used, so I would recommend looking here: https://developers.google.com/maps/documentation/ios-sdk/marker and see what's possible when it comes to GoogleMaps on iOS before attempting to use it.

**Comment by artkrv** [comment]
Make sure you do not pass any undefined values to Animated.View (Map).

**Comment by schriker** [comment]
I'm facing the same issue when trying to cluster markers and if the point is a cluster render circle with the number of points. Is there any workaround to render such a custom marker without crashing?

**Comment by pke** [comment]
@salah-ghanim @ingvardm This only started to happen when upgrading react-reanimated to 2.10.0 version. Before it worked fine even with such markers. So its about some interdependency in the animation core it seems.

**Comment by Rutvik17** [comment]
> Using the Apple Maps implementation on iOS solves the problem for me (i.e. dropping the `provider={PROVIDER_GOOGLE}` prop).



> This happens only when the marker has children. For my solution i can use images instead of nested views on iOS, see if you can do the same. Also you can try getting the position of thee marker (onLayout) and use that to place your whatever on top of it.

Above both fix this problem for me.

**Comment by WillyRamirez** [comment]
> @salah-ghanim @ingvardm This only started to happen when upgrading react-reanimated to 2.10.0 version. Before it worked fine even with such markers. So its about some interdependency in the animation core it seems.

@pke Can you please tell me with which version you got it to work? I tried downgrading react-native-reanimated to version 2.9.1 and 2.3.3 but I keep getting the same error

**Comment by rjdestigter** [comment]
> but Google Maps don't support native UIKit Views (I think they even render using openGL). so when react native tries to create a view inside the Marker .. everything breaks.

I'm not convinced this is the case since the markers do render the first time no problem. The issue seems to be when a key is dropped. This would explain why some developers are mentioning using indexes as a key rather than ids.

**Comment by davedoescode** [comment]
Originally posted this comment on a separate issue thread, but figured I would post here since this thread has a lot of activity.

I have written a blog post if you are interested in reading about my solution a little bit more, but if not, I'll add the TL;DR in this comment.

[Here's the blog post](https://dev.to/jobber/custom-google-map-markers-on-ios-with-react-native-maps-1m2n)

### And here is the TL;DR:

If you are getting the error `Exception thrown while executing UI block: * -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil` while trying to use custom markers with Google Maps on iOS via react-native-maps, it is possible the root cause is a conflict with react-native-reanimated.

I don't know exactly what the conflict is, however, I have two solutions that may work for you!

#### Solution 1

If feasible, you can remove react-native-reanimated from your project and that should resolve the issue for you.

If that isn't an option, I would encourage you to rebuild your map in a test project without reanimated, and implement your map so that you are using custom markers (and it should work). Then, reintroduce reanimated into that project, and add your desired functionality in piece wise until you can isolate what method in reanimated is causing the error. In our case, it was our use of `FadeInUp` and `FadeInOut`. Your mileage may vary, but you should be able to find alternative animation solutions while preserving your app's behaviour.

#### Solution 2

Agnostic of any react-native-reanimated conflicts, this error is thrown because the indices from the marker array you're mapping over are bring dropped in the case that the marker array length, `n`, is changing such that `n' < n`.

You can create a hook that will always return a constant sized array containing marker objects to your map view, so that it may map your objects to custom markers. For every index in this array, there will exist either a real marker object that renders on the map, or a buffer object that will not render on the map. Either way, the indices being used as keys will always exist, therefore you will not hit this error.

**Comment by suminc7** [comment]
I solved it like below.
```
    const [isLayout, setLayout] = useState(false);

    const onLayout = () => {
      setLayout(true);
    };
    ...

  <MapStyledView
    onLayout={onLayout}
        ...
    <Marker
      key={'startMarker'}
      coordinate={}}>
      {isLayout && <MarkerItem />}
    </Marker>
```

**Comment by jinliming2** [comment]
I just solved this by upgrading my `"react-native-reanimated"` to `"^3.0.0-rc.10"`. (was `3.0.0-rc.3`).
I checked the change log, and I think this bug was related to `entering` and `exiting` props of reanimated.

**Comment by urkin-dev** [comment]
> I just solved this by upgrading my `"react-native-reanimated"` to `"^3.0.0-rc.10"`. (was `3.0.0-rc.3`). I checked the change log, and I think this bug was related to `entering` and `exiting` props of reanimated.

That fixed it for me thanks

**Comment by Hopefulee** [comment]
@jinliming2 - thanks u saved my life

**Comment by saad9624-tribalScale** [comment]
_notifyAboutProgress Getting this after installing  ^3.0.0-rc.10

**Comment by x-iceman** [comment]
I am facing this issue after after installing ^3.0.0-rc.10 
[!] Unable to find a specification for `React-hermes` depended upon by `RNReanimated`

**Comment by bourkison** [comment]
Expo 49 supports reanimated 3.3.0 and resolves the issue for me.

**Comment by NiccoloCase** [comment]
have anyone a better solution? we can't update reanimated because of a bug of the new v3

**Comment by divyong** [comment]
> have anyone a better solution? we can't update reanimated because of a bug of the new v3

same trouble, and I've been looking for a solution for quite a long time

**Comment by ingvardm** [comment]
Has anyone tryed something like removing the markers first and then remove the MapView on the next frame?

**Comment by kdvmgn** [comment]
I tried to prevent the app from crashing by adding a null check before inserting or removing the subview in `AIGGoogleMap.m`:
``` obj-c
- (void)insertReactSubview:(id<RCTComponent>)subview atIndex:(NSInteger)atIndex {
  ...
  // Add nil safety check to prevent crashes when markers are dynamically updated during zoom
  if (subview != nil) {
    NSUInteger safeIndex = MIN((NSUInteger)atIndex, [_reactSubviews count]);
    [_reactSubviews insertObject:(UIView *)subview atIndex:safeIndex];
  } else {
    NSLog(@"[AIRGoogleMap] Warning: Attempted to insert nil subview at index %ld", (long)atIndex);
  }
}

- (void)removeReactSubview:(id<RCTComponent>)subview {
  ...
  // Add nil safety check to prevent crashes during marker removal
  if (subview != nil) {
    [_reactSubviews removeObject:(UIView *)subview];
  } else {
    NSLog(@"[AIRGoogleMap] Warning: Attempted to remove nil subview");
  }
}
```
I know it doesn't address the root issue, but seems like helping to prevent the crash. I'm gonna use it as a workaround.
