### ISSUE TITLE
Error while updating property InitialRegion

### ISSUE THREAD

**Issue by mpn7** [react-native-maps/react-native-maps#4256]
### Summary

When using your most most basic example I get the error: 
"Error while updating property 'initialRegion' of a view managed by: AIRMap

This happens whenever I use the prop `initialRegion`

### Reproducible sample code

```TSX
return (
        <View style={{flex: 1}}>
        
            <MapView
              initialRegion={{
                latitude: 37.78825,
                longitude: -122.4324,
                latitudeDelta: 0.0922,
                longitudeDelta: 0.0421,
              }}
            />
          
        </View>
      );
```

### Steps to reproduce

Just start the app using the initialRegion prop.

### Expected result

Not to give an error on app start.

### Actual result

![167765922-9d227b27-ffb5-4376-a888-3c52604e77b2](https://user-images.githubusercontent.com/50495592/170952011-115c207d-0132-444a-9236-93e8fccdd279.png)

### React Native Maps Version

0.31.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.64.3

### Are you using Expo?

Yes

### Device(s)

One Plus 6

**Comment by CyrilAnac** [comment]
Same problem

**Comment by kersa901** [comment]
Same problem

**Comment by tbessenreither** [comment]
Same here:
Expo 44
react: 17.0.1
react-native 0.64.3

**Comment by kersa901** [comment]
Expo 45.0.0
react 17.0.2
react-native 0.68.2

**Comment by Off2Race** [comment]
I just upgraded my non-Expo app to version 0.31.1 and I'm having a similar issue. The error message is slightly different but the experience appears the same as the previous comments. I'm including the full screenshot below in case the call stack is useful.

"react": "17.0.2",
"react-native": "0.67.4",
"react-native-maps": "0.31.1",

If I switch to the region prop instead of initialRegion, the error stops. If I revert back to version 0.30.1, all works ok too.

I have no issues with 0.31.1 on iOS. Only with Android (Pixel 4, API 30 emulator).

I tried the new enableLatestRenderer function but the result is the same whether I call it or not.

![image](https://user-images.githubusercontent.com/2400179/176047506-17b68c77-ab52-4547-87e7-5f1a310b60a7.png)

**Comment by Simon-TechForm** [comment]
Wanted to look into this, but I'm unable to reproduce the issue. @Off2Race you aren't using expo - could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Off2Race** [comment]
Hi, @Simon-TechForm – Thanks for responding. Yes, I'll re-update to 0.31.1 and try to reproduce again.

**Comment by Simon-TechForm** [comment]
Is anyone able to provide a minimal reproducible example? Maybe a snack or a repository?

**Comment by Off2Race** [comment]
Hi, @Simon-TechForm – My apologies for not getting back to you sooner. I've been testing with 0.31.1 for nearly 2 weeks now and I cannot make the error happen again. I haven't released it to users yet but I don't see any reason why I won't push it out with the next release.

At this point, I have to assume the error I saw was caused by something bogus in the data I was passing to initialRegion. I wish I knew what it was so I could guard against it but I cannot make the error happen now.

As far as I'm concerned, 0.31.1 works great. Thanks again for following up.
