### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by nilpatil7744** [react-native-maps/react-native-maps#4513]
### Summary

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Reproducible sample code

```TSX
///this code snippet shows how i am using it in the project
     <MapView
          onRegionChangeComplete={onRegionChange}
          // provider={PROVIDER_GOOGLE}
          style={{ height: mapheight }}
          customMapStyle={mapStyle}
          region={{
            latitude: userLatitude,
            longitude: userLongitude,
            latitudeDelta: 0.015,
            longitudeDelta: 0.0121,
          }}
          scrollEnabled={true}
        >
          <Marker
            coordinate={{
              latitude: userLatitude,
              longitude: userLongitude,
            }}
            title={'test'}
          />
        </MapView>
```

### Steps to reproduce

when i am trying to run my project its throwing the error screen this due to the marker when i commented marker i was able to see the Map the issue is in Marker import or something regarding to that.

<img width="1440" alt="Screenshot 2022-11-04 at 1 08 49 PM" src="https://user-images.githubusercontent.com/77038652/199920153-39d9d7f8-b1b6-4567-bb82-2dce11e13a9c.png">

### Expected result

expected result is marker should show in my project on the website MAP.

### Actual result

marker should show in my projectexpected result is marker should show in my project on the website MAP. on the website MAP

### React Native Maps Version

1.3.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.66.2

### What version of Expo are you using?

Not using Expo

### Device(s)

mac google chrome web view

### Additional information

we are using the   "react-native-maps": "^1.3.1" this version in the project and platform.OS is web

**Comment by femotizo** [comment]
@nilpatil7744  I experienced same issue today found out that..  Marker, Circle and the rest are no longer a member of MapView, so you can't call/use it without importing it,

Import the Marker component like below:

`import MapView, {Marker, Circle} from 'react-native-maps';`


Please can you share more on how you imported it.

Reference below:
#4332

**Comment by Simon-TechForm** [comment]
`react-native-maps` is only supported on Android and iOS, not web. :)

**Comment by nilpatil7744** [comment]
do the react-native-maps not supported platform.OS based on OS it shows it
in the react-native-web it worked earlier for me not now in my old code its
working with new project its not working in react-native web can uh comment
on this

**Comment by forwells** [comment]
In my case, it was due to a component import namespace issue, which I spent a lot of time dealing with.
In fact, returning to the original bug solution, we can trace the problem through the component corresponding to the url.

The full error message I encountered:
![image](https://user-images.githubusercontent.com/32950945/210329462-196a7075-930b-43e6-8bf6-4b7663473738.png)
Then I opened the link in the error message:
![image](https://user-images.githubusercontent.com/32950945/210329572-486451a8-7e7e-4f9e-9298-89663422ba19.png)
According to some hints on stackoverflow, there may be problems caused by the namespace when the component is imported, so I checked the component corresponding to the current route, and found that some UI components were not imported in the normal way (according to some components Design rules, here is likely to cause some problems with associated dependency types)

Check out the comparison of the two screenshots I made here:

![image](https://user-images.githubusercontent.com/32950945/210329920-693f4f4d-4195-4358-9882-e0d28d95f919.png)
The normal import here should be import {Layout} from 'antd'
![image](https://user-images.githubusercontent.com/32950945/210330087-f334ca97-b647-4a45-a362-a47a42aae773.png)
Then I submitted the component to build:client
After that everything works fine, I hope it can help everyone
Tip: Not only the components directly specified by the current route (such as react-router), but also the subcomponents nested in the root component corresponding to the route need to be checked accordingly, and imported with the correct import namespace. After that, the problem should be solved solve

**Comment by Minh-ka** [comment]
> @nilpatil7744 I experienced same issue today found out that.. Marker, Circle and the rest are no longer a member of MapView, so you can't call/use it without importing it,
> 
> Import the Marker component like below:
> 
> `import MapView, {Marker, Circle} from 'react-native-maps';`
> 
> Please can you share more on how you imported it.
> 
> Reference below: #4332

Thanks bro, it helped me today
