### ISSUE TITLE
Request of user location not working when use default provider on ios

### ISSUE THREAD

**Issue by artyom-ivanov** [react-native-maps/react-native-maps#4651]
### Summary

if I use the google maps provider, then the request for the user's location appears automatically. If I use apple maps (the default provider), then the request does not appear.

### Reproducible sample code

```TSX
<MapView
  ref={(ref) => (map.current = ref)}
  style={{ flex: 1 }}
  provider={
    settings.preferredMap === 'apple'
      ? PROVIDER_DEFAULT // REQUEST NOT APPEARS
      : PROVIDER_GOOGLE // REQUEST APPEARS
  }
  showsUserLocation
  onUserLocationChange={handleLocation}
  initialRegion={INITIAL_REGION}
  onRegionChange={changeLocation}
/>
```

### Steps to reproduce

Run app on clean simulator with apple map by default and "showsUserLocation" prop on Map component.

### Expected result

Request about user location appears

### Actual result

Request not appears

### React Native Maps Version

1.1.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.69.1

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 13 mini simulator, iPhone 12 pro max

**Comment by Simon-TechForm** [comment]
Hello @artyom-ivanov 👋

This is the expected behaviour. Google decided to build it into the Google Maps SDK which is the only reason why it's there for Google Maps. I'm a firm believer that it isn't the responsibility of `react-native-maps` to request location permissions. The behaviour is documented in [the docs](https://github.com/react-native-maps/react-native-maps/blob/master/docs/mapview.md).

**Comment by devshahzad56** [comment]
Nice
