### ISSUE TITLE
Blank map (or sometimes with only markers) shown when I start the app after installation - for first 2-3 times. Then after that it works correctly itself.

### ISSUE THREAD

**Issue by Vikas-Mehra** [react-native-maps/react-native-maps#4819]
### Summary

After I install my app, for first 2-3 times , when I start the app (i.e. restarting the app for 2-3 times), blank-map is shown with google-logo (or sometimes with only markers). 
Then after 3rd-time generally, it works correctly itself.

### Reproducible sample code

```TSX
.
```

### Steps to reproduce

 .

### Expected result

It should work correctly (like after 3rd time in this case). That is the map should be visible from 1st time opening the app.

### Actual result

.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.72.1

### What version of Expo are you using?

Not using Expo

### Device(s)

All

**Comment by salah-ghanim** [comment]
@Vikas-Mehra  this issue is closed because the formula is ignored.

Please provide a sample code with bare minimum to reproduce and we're happy to look into it.

on my side I can confirm that if the lib is setup correctly and used correctly there shouldn't be an issue with displaying markers or anything else on android, iOS .. we have apps with 100k+ users and everything works fine on all kind of android / iOS devices.
