### ISSUE TITLE
[Apple Maps] Polygon holes don’t re-render if updated

### ISSUE THREAD

**Issue by austin-liou** [react-native-maps/react-native-maps#4864]
### Summary

When using the default provider in iOS, if holes are updated, the polygons don’t re-render and update the holes. This is not an issue for the Google provider in iOS.

We are not blocked - the workaround is to wait on rendering the map until the holes are loaded.

### Reproducible sample code

```TSX
import React from 'react';
import View from 'react-native';
import { LatLng, MapView, Polygon } from 'react-native-maps';

export default function App() {
  const holes = useHoles();

  return (
    <View style={{ flex: 1}} >
      <MapView style={{ flex: 1}}>
        <Polygon
          coordinates={[
            { latitude: 10, longitude: 10 },
            { latitude: 10, longitude: 20 },
            { latitude: 20, longitude: 20 },
            { latitude: 20, longitude: 10 }
          ]}
          holes={holes}
          fillColor={'green'}
        />
      </MapView>
    </View>
  );
}

function useHoles() {
  const [holes, setHoles] = React.useState<LatLng[][]>([]);

  useEffect(() => {
    // Doing it this way because computing may be expensive or otherwise side-effecty
    setHoles([
      [
        { latitude: 13, longitude: 13 },
        { latitude: 13, longitude: 17 },
        { latitude: 17, longitude: 17 },
        { latitude: 17, longitude: 13 }
      ]
    ]);
  }, []);

  return holes;
}
```

### Steps to reproduce

Run the above code snippet. You’ll have to scroll the map over to Africa to see the polygon.

If you pass the holes object directly into the `Polygon` instead (i.e., on mount), the hole will render properly.
If you use the Google provider, the hole will render properly.

### Expected result

I expect the holes to be updated when they are set.

### Actual result

The holes are never rendered if they are not passed in on mount.

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.3

### What version of Expo are you using?

SDK 48

### Device(s)

iPhone 14 Plus, iPhone 12

### Additional information

We are actually using Expo SDK 49, but it’s not available in the list above :)

**Comment by austin-liou** [comment]
cc @deancampagnolo

**Comment by Ahmedhamed77** [comment]
@austin-liou 
hello, I hope you are doing well
as I understand your points that are coming from `const holes = useHoles();` not updated on the first mount as expected

this is a common behavior of React: when using complex data structures like arrays or objects, if the data is structurally the same (from a reference point of view), React will not re-render the component. This is because React uses a shallow comparison by default.

so there is a simple solution to re-render it
by using the key prop. This prop can force a re-render if its value changes. So, for your Polygon component, you can use the length of the holes array as a key:

```
 <MapView style={{flex: 1}}>
        <Polygon
          coordinates={[
            {latitude: 10, longitude: 10},
            {latitude: 10, longitude: 20},
            {latitude: 20, longitude: 20},
            {latitude: 20, longitude: 10},
          ]}
          holes={holes}
          key={holes.length} // add this
          fillColor={'green'}
        />
</MapView>
   ```   
 even if the length of the array will not change you might face another problem
 maybe you will also you need to Deep clone to update your data whenever you want 
 
 if I don't understand correctly what you meant here please correct me

**Comment by austin-liou** [comment]
@Ahmedhamed77 oh… 🤦🏼 that’s a good point. We’ll give this a shot and let you know! Thanks so much
