### ISSUE TITLE
glCreateShader failed with return value 0and GL error code 0

### ISSUE THREAD

**Issue by deepakv-z14** [react-native-maps/react-native-maps#4884]
### Summary

I am using rect-native-maps in my android application and it is crashing randomly on the production app with below error

```
Fatal Exception: m.evv: glCreateShader failed with return value 0and GL error code 0
GL info log: 
<no info log>
Shader vert source: 
<unused source>
       at m.esv.b(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:71)
       at m.esv.a(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:4)
       at m.etr.<init>(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:32)
       at m.ets.<init>(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:6)
       at m.esq.run(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:119)
 ```

### Reproducible sample code

```TSX
import React from 'react';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps';

const LATITUDE_DELTA = 0.0002;
const LONGITUDE_DELTA = 0.009;

export default function App() {
  return (
    <MapView
      ref={mapRef}
      toolbarEnabled={false}
      onMapReady={onLayout}
      zoomEnabled={false}
      scrollEnabled={false}
      pitchEnabled={false}
      provider={PROVIDER_GOOGLE}
      moveOnMarkerPress={false}
      style={{ ...StyleSheet.absoluteFillObject }}
      showsMyLocationButton={false}
      maxZoomLevel={18}
      minZoomLevel={14}
      mapPadding={{
        top: 0,
        right: 20,
        bottom: 0,
        left: 20,
      }}
      initialRegion={{
        latitude: 37.774929,
        longitude: -122.419418,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      }}>
      <Marker coordinate={{ latitude: 37.774929, longitude: -122.419418 }}>
        <Image source={{ uri: 'imageurl' }} style={{ height: 20, width: 20 }} />
      </Marker>
    </MapView>
  );
}
```

### Steps to reproduce

Show map

### Expected result

should not crash

### Actual result

crashing with error `m.evv: glCreateShader failed with return value 0and GL error code 0`

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

Android

### React Native Version

0.71.12

### What version of Expo are you using?

Not using Expo

### Device(s)

Vivo V2111, Oppo A78 5G

**Comment by jan-kozinski** [comment]
Hi, did you manage to reproduce the error with the sample code you provided? I can't reproduce it. It's most likely a bug in the google maps SDK itself since we're not using openGL directly anywhere in the project. I've found a similar issue on google-maps-flutter https://github.com/flutter/flutter/issues/130712. You can try adding these lines 
```
import { enableLatestRenderer } from 'react-native-maps';

enableLatestRenderer();
``` 
To your App.tsx. Note that the `enableLatestRenderer` should not be called inside of the App component but above it.

**Comment by salah-ghanim** [comment]
@jan-kozinski  thanks for the support here ... I agree as well react-native-maps doesn't use openGL code directly ... so whatever the reason is, it has something to do with google maps.

@deepakv-z14 I advice that you submit the ticket to google maps or try using a different SDK version... there isn't much we can do unfortunately to support you here.

also @deepakv-z14 please make sure you use https://github.com/react-native-maps/react-native-maps/#rendering-a-marker-with-a-custom-image ... crashes often happen due to resizing issues.

**Comment by OkancanCosar** [comment]
@deepakv-z14    is there any solution for image prop with style? 
stuck with android poor performans :(
