### ISSUE TITLE
Change iOS compass offset dynamically [Feature request / Bug]

### ISSUE THREAD

**Issue by mateki0** [react-native-maps/react-native-maps#4916]
### Summary

Hi, in our project we have a compass that has a starting offset position based on other components on the screen. After few seconds of scrolling the map we are hiding those components and it would be nice to move compass to the top of the screen. Currently it is not possible to change compass position dynamically.

### Reproducible sample code

```TSX
import React, { useState } from 'react'
import MapView from 'react-native-maps'

export const BaseMapView = () => {
  const [compassOffsetY, setCompassOffsetY] = useState(150);

  const onOtherComponentsHide = () => {
    setCompassOffsetY(20)
  }

  // Call the otherComponentsHide after 6 seconds of scrolling the map or whatever action
  // to reproduce it could be even onPress event
  return (
    <MapView compassOffset={{x: 0, y: compassOffsetY}}/>
  )
}
```

### Steps to reproduce

Use provided code reproducible code and try to modify compass offset.

### Expected result

Compass will move from y=150 to y = 20.

### Actual result

Compass stays at his initial position.

### React Native Maps Version

1.8.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.72.4

### What version of Expo are you using?

Not using Expo

### Device(s)

iPhone 15

### Additional information

The main point of this issue is to get information if such a feature will be helpful for anyone or if it's only our, very edge case problem. I couldn't open an issue with another label and I would say that it's not a bug, but rather a missing feature.

**Comment by salah-ghanim** [comment]
@mateki0 Thank you for your request, as you mentioned this is not a bug since it's not an unexpected behaviour.

and yes as you mentioned it's such a niche request it doesn't make sense for us to consider adding it to the library itself.

I would recommend that you look into:
https://stackoverflow.com/questions/48343381/how-to-reposition-compass-of-mkmapview

seems very possible to apply your package patch to this library where you add some native / JS glue to modify the functionality of MKMapView without having to maintain your own fork of the library.

https://github.com/ds300/patch-package
