### ISSUE TITLE
Infinite loop when zoom is out

### ISSUE THREAD

**Issue by kicaal** [react-native-maps/react-native-maps#4926]
### Summary

When I do zoom out, comes a time that the change region function enter in infinity loop, only happened with PROVIDER_GOOGLE in IOS

https://github.com/react-native-maps/react-native-maps/assets/40881553/a3954848-e364-4be7-a71c-039c7f980fcf

### Reproducible sample code

```TSX
<MapView
        style={styles.map}
        customMapStyle={mapStyle}
        initialRegion={userLocation}
        region={currentLocation}
        onRegionChangeComplete={(region) => {
          onChangeLocation(region)
        }}
        provider={PROVIDER_GOOGLE}
        mapType="standard"
        moveOnMarkerPress={false}
        showsMyLocationButton={false}
        rotateEnabled={false}
        showsUserLocation
        followsUserLocation
        paddingAdjustmentBehavior="never"
      >
</MapView>
```

### Steps to reproduce

Only zoom out

### Expected result

Don't do infinity loop

### Actual result

Infinity loop when i zoom out

### React Native Maps Version

1.8.4

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.73.1

### What version of Expo are you using?

Using Expo 49.0.21

### Device(s)

Iphone 13, Iphone SE 3rd generation

**Comment by mateki0** [comment]
Hi @kicaal, thanks for reporting this. It's a known problem and you can fix it with adding simple if statement to your **onChangeLocation** function.

```tsx
export default function Map() {
  const onChangeLocation = (region, gesture) => {
    if(!gesture.isGesture) { 
      return 
    }

    // rest of your logic
  }

  return (
    <View style={{ flex: 1 }}>
      <MapView
        style={{flex:1}}
        customMapStyle={mapStyle}
        initialRegion={userLocation}
        region={currentLocation}
        onRegionChangeComplete={(region, gesture) => {
          onChangeLocation(region, gesture)
        }}
        ...
```

source: https://github.com/react-native-maps/react-native-maps/issues/846#issuecomment-1210079461

**Comment by kicaal** [comment]
Hi! [mateki0](https://github.com/mateki0), thanks for your response it is very helpful! That solve my problem!

The maintainers are working to prevent use that if?

Thank you!

**Comment by salah-ghanim** [comment]
@kicaal I just reviewed what's going on and it's clear to me why it happens.

Apple is providing reliable synchronous callbacks for when a region change happens and so it's easy to write on iOS a code that looks like this:
blockPropagatingRegionChange
applyRegionChange
resetRegionChangePropagationState

the callback to regionDidChange happens inside this block which means the event will not be propagated back to JS because the event sending is being blocked.

with google maps, the callbacks are async and there is no way to know for sure that the callback is happening due to a specified queued change (for example a user interaction can happen at the same time or an animation hasn't finished yet)

because of this I don't see any way to correctly fix this, so using the gesture flag to make sure you exit an endless loop sounds like a good solution.
