### ISSUE TITLE
Scale Bar / ShowsScale feature request

### ISSUE THREAD

**Issue by BennyCarlsson** [react-native-maps/react-native-maps#4953]
### Summary

Is it possible to get a Scale Bar for google maps and some options for the iOS map?

At the moment the prop showsScale only shows a scale bar on iOS and apple maps and is not supported on google maps. It also only shows while zooming and you cant style or place it anywhere.
For android or google maps this is not supported at all.

Is there any alternativ to show a Scale Bar?

### Reproducible sample code

```TSX
<MapView showsScale />
```

### Steps to reproduce

<MapView showsScale/> 

Just look at:
Google Maps on Android
Apple Maps on iOS

### Expected result

I want a Scale Bar to always be showing on iOS / Apple Maps and Android / Google Maps

### Actual result

Only shows a Scale bar while zooming on Apple Maps.

### React Native Maps Version

1.8.3

### What platforms are you seeing the problem on?

Android, iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.72.4

### What version of Expo are you using?

Not using Expo

### Device(s)

Iphone 12, Google pixel 6

**Comment by salah-ghanim** [comment]
@BennyCarlsson I just googled and found this:
https://github.com/grethi/CHGMapView

it seems like you can layout a view on top of your map that updates graphic to display scale / zoom level ... I don't see the need to do this inside the library itself since the zoom level is always available and can be used to create such a component.

**Comment by furkanndemirr** [comment]
Did you find the answer to this question?
