### ISSUE TITLE
I use OSM but in the bottom show the GOOGLE

### ISSUE THREAD

**Issue by ikaaasra** [react-native-maps/react-native-maps#4967]
### Summary

I use OSM for my MapView but in the bottom Show me the GOOGLE 

### Reproducible sample code

```TSX
<MapView
          style={StyleSheet.absoluteFillObject}
          mapType="none"
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
            latitudeDelta: 0.0922,
            longitudeDelta: 0.0421,
          }}
          provider={undefined}
          rotateEnabled={false}
          maxZoomLevel={19}
        >
          <UrlTile
            urlTemplate="https://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png"
            shouldReplaceMapContent={true}
            maximumZ={19}
            tileSize={512}
            flipY={false}
          />
        </MapView>
```

### Steps to reproduce

I want to remove GOOGLE from the bottom

### Expected result

add a option to remove google 

### Actual result

add a option to remove google 

### React Native Maps Version

1.10.0

### What platforms are you seeing the problem on?

Android

### React Native Version

0.73.4

### What version of Expo are you using?

SDK 48

### Device(s)

Android and iPhone

**Comment by mateki0** [comment]
Hi, @i1kaaasra  I don't think it's possible. You are still using google maps underneath and OSM is just an overlay. We can't add option to disable Google text because it violates their license restrictions.

"(b) Attribution.  Customer will display all attribution that (i) Google provides through the Services (including branding, logos, and copyright and trademark notices); or (ii) is specified in the Maps Service Specific Terms. Customer will not modify, obscure, or delete such attribution."  - 3.2.2 Requirements for Using the Services

Source: https://cloud.google.com/maps-platform/terms/#10-license-restrictions

**Comment by i1kaaasra** [comment]
I use OSM ... and I do not use Google Map

**Comment by mateki0** [comment]
Even though you are still using one of the two providers to render the whole map under the Tile.
As it is said in the documentation:

```
The map framework to use.

Either "google" for GoogleMaps, otherwise null or undefined to use the native map framework (MapKit in iOS and GoogleMaps in android).
```
