### ISSUE TITLE
UIScreen' is unavailable: not available on visionOS

### ISSUE THREAD

**Issue by purevsurena** [react-native-maps/react-native-maps#5047]
### Summary

When integrating the react-native-maps library with a React Native app that utilizes the callstack/react-native-visionos library for visionOS development, a build error occurs. The error, as shown in the attached screenshot, indicates a Library not found for -lGoogleMaps issue. This issue prevents successful app compilation and might be related to compatibility between the two libraries.
<img width="270" alt="Screenshot 2024-05-09 at 11 31 10" src="https://github.com/react-native-maps/react-native-maps/assets/35187128/a48fb7b8-70ce-43b8-9685-31b4acc12ac8">

### Reproducible sample code

```TSX
<MapView
   style={{ flex: 1, backgroundColor: Colors.white100 }}
   initialRegion={region}
   provider={PROVIDER_GOOGLE}
   region={region}
   showsUserLocation
   onRegionChangeComplete={onRegionChangeComplete}
   clusterColor="#703ED9"
>
```

### Steps to reproduce

1. Create a React Native project with callstack/react-native-visionos.
2. Install react-native-maps using the recommended installation method.
3. Attempt to build the app.
4. Observe the build error.

### Expected result

The app should compile successfully and include react-native-maps functionality.

### Actual result

The builds fail with the error Library not found for -lGoogleMaps.

### React Native Maps Version

1.15.1

### What platforms are you seeing the problem on?

iOS (Apple Maps), iOS (Google Maps)

### React Native Version

0.73.6

### What version of Expo are you using?

Not using Expo

### Device(s)

VisionPro Simulator

**Comment by salah-ghanim** [comment]
@purevsurena google-maps-sdk is not compatible with visionOS, see releases by google here:
https://developers.google.com/maps/documentation/ios-sdk/release-notes
I believe that the MapKit from apple works with visionOS, but I haven't tested so:
1. please use react-native-maps pod instead of react-native-google-maps pod.
2. you can try to exclude the GoogleMaps Pod from visionOS build, for that you need to look outside this lib since it's a generic xcode build config (excluding dependency from a specific OS / target).

I'm closing this issue as out of scope.
