### ISSUE TITLE
How can we handle disputed territory in google map

### ISSUE THREAD

**Issue by numandev1** [react-native-maps/react-native-maps#5089]
### Summary

if I open Google map from Saudia then it shows the Arabian gulf and if I open a map from outside of Saudia than it shows the Persian Gulf, but this package Is always showing the Persian gulf, as I am making an app for a Saudi company so I wanna make it Arabian gulf, how can I do this?

### Reproducible sample code

```TSX
n/a
```

### Steps to reproduce

- open the Native Google Map app from Saudia it will show Arabian gulf
- then open the react native app which is using react-native-app, you will see Persian gulf which is wrong for our Saudia company app 

### Expected result

i want to make the Persian gulf into Arabian Gulf

### Actual result

it shows showing Persian Gulf instead of the Arabian gulf

### React Native Maps Version

1.7.1

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.70.0

### What version of Expo are you using?

SDK 48

### Device(s)

iphone 13 pro max

**Comment by salah-ghanim** [comment]
@numandev1 this would be an issue in the google-maps SDK itself, you should be able to setup a sample google maps iOS app and test that locale based feature such as geographical feature naming is different between locations.


this could be solved also by using a custom google cloud based map where you can modify a lot of map features, but unfortunately for iOS this is not supported yet in this library because of an open pull request here:
https://github.com/googlemaps/google-maps-ios-utils/pull/451
