### ISSUE TITLE
iOS onMapPress called when marker pressed

### ISSUE THREAD

**Issue by stevekuznetsov** [react-native-maps/react-native-maps#5246]
### Summary

We were previously following https://github.com/react-native-maps/react-native-maps/issues/1132 to stop propagation of events, but this seems to no longer work after we upgraded to Expo 52 and react-native-maps@1.18.0 from Expo 51 and react-native-maps@1.14.0. 

### Reproducible sample code

```TSX
I understand the value of a reproducer but can't invest the time to isolate this right now. Please see our use of stopPropagation here: https://github.com/NWACus/avy/blob/74aa62f729348cc5ddc52a8b0ab50f52d79b1a13/components/map/AvalancheForecastZonePolygon.tsx#L72-L75
```

### Steps to reproduce

See above.

### Expected result

The default onPress is not called.

### Actual result

The default onPress is called.

### React Native Maps Version

1.18.0

### What platforms are you seeing the problem on?

iOS (Apple Maps)

### React Native Version

0.76.3

### What version of Expo are you using?

SDK 52

### Device(s)

iPhone 12

**Comment by stevekuznetsov** [comment]
Could be related?

https://github.com/react-native-maps/react-native-maps/commit/b2d2fd8cddb8808a41ae881f87a7295ac78f5b06

**Comment by salah-ghanim** [comment]
@stevekuznetsov 
I'm closing this issue because it's all related to the same topic updating to support Fabric / latest react native

you can see in the readme that it's not supported yet here:
https://github.com/react-native-maps/react-native-maps/?tab=readme-ov-file#important-notes

and you can follow up here on the progress:
https://github.com/react-native-maps/react-native-maps/issues/5206

**Comment by stevekuznetsov** [comment]
I've disabled the new architecture in my project (we're on Expo) and was still seeing this bug. Nevertheless, thanks for looking.
